# Hypothesis testing
Name: SAI AKHIL SN | Batch date: 27 Jan 2021

In [1]:
# Importing necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
from scipy import stats

### Hypothesis testing exercise 1

In [2]:
cutlet_df = pd.read_csv("C://Users/Oftog/Downloads/Cutlets.csv")
cutlet_df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [3]:
cutlet_df.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [4]:
cutlet_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Unit A  35 non-null     float64
 1   Unit B  35 non-null     float64
dtypes: float64(2)
memory usage: 688.0 bytes


In [5]:
# checking for null values
cutlet_df.isnull().sum()

Unit A    0
Unit B    0
dtype: int64

In [6]:
# Interpreting t value
stats.t.ppf(0.975,34)

2.032244509317718

In [7]:
stats.t.cdf(2.0322,34)

0.9749976292019064

In [8]:
a=cutlet_df['Unit A']

In [9]:
b=cutlet_df['Unit B']

In [10]:
stats.ttest_ind(a,b)

Ttest_indResult(statistic=0.7228688704678061, pvalue=0.4722394724599501)

### Hypothesis testing exercise 2

In [11]:
lab_df=pd.read_csv("C://Users/Oftog/Downloads/labTAT.csv")
lab_df.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [12]:
lab_df.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [13]:
# Extracting individual columns
Lab1=lab_df.iloc[:,0]
Lab2=lab_df.iloc[:,1]
Lab3=lab_df.iloc[:,2]
Lab4=lab_df.iloc[:,3]

In [14]:
# calculating variance for individual columns
Lab1.var(),Lab2.var(),Lab3.var(),Lab4.var()

(173.54356806022412,
 223.71525108543426,
 273.53960699579824,
 227.55963186974788)

In [15]:
# Performing Anova test
stats.f_oneway(Lab1,Lab2,Lab3,Lab4)

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

### Hypothesis testing exercise 3

In [16]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [17]:
buyer_data=pd.read_csv("C://Users/Oftog/Downloads/BuyerRatio.csv")
buyer_data

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [18]:
buyer_data.describe()

East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [19]:
df=[[50,142,131,70],[550,351,480,350]]

In [20]:
df

[[50, 142, 131, 70], [550, 351, 480, 350]]

In [21]:
stat,p,dof,expected = chi2_contingency(df)
print(f'P-value = {p}')
print(f"Degrees of freedom = {dof}")
print(expected)

#interpreting the T-statistic

prob=0.95
critical =chi2.ppf(prob,dof)
print(f"probability = {prob}, critical = {critical}, stat = {stat}")
if abs(stat)>=critical:
    print('Dependent so reject Null hypothesis (H0)')
else:
    print('independent so accept Alternate hypothesis (Ha)')
    
#interpreting the P-value:

alpha=1.0 - prob
print(f"alpha = {alpha}, p_value = {p}")
if p<=alpha:
    print("Dependent so reject null hypothesis (H0)")
else:
     print('independent so accept alternate hypothesis (Ha)')

P-value = 2.682172557281901e-17
Degrees of freedom = 3
[[111.01694915  91.21892655 113.05225989  77.71186441]
 [488.98305085 401.78107345 497.94774011 342.28813559]]
probability = 0.95, critical = 7.814727903251179, stat = 80.27295426602495
Dependent so reject Null hypothesis (H0)
alpha = 0.050000000000000044, p_value = 2.682172557281901e-17
Dependent so reject null hypothesis (H0)


In [22]:
stats.chi2.ppf(0.95,df=3)

7.814727903251179

In [23]:
a=[50,142,131,70]
b=[550,351,480,350]

### Hypothesis testing exercise 4

In [24]:
customer_df=pd.read_csv("C://Users/Oftog/Downloads/Costomer+OrderForm.csv")
customer_df.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [25]:
600*393

235800

In [26]:
235800/2124

111.01694915254237

In [28]:
# df=pd.read_csv('C://Users/Oftog/Downloads/Fantaltoons.csv')

In [29]:
df2 = [[29,33,31,20],[271,267,269,280]] 
df2

[[29, 33, 31, 20], [271, 267, 269, 280]]

In [30]:
stat2,p2,dof2,expected2 = chi2_contingency(df2)
print(f'P-value = {p}')
print(f"Degrees of freedom = {dof2}")
print(expected)

#interpreting the T-statistic

prob2=0.95
critical2 =chi2.ppf(prob2,dof2)
print(f"probability = {prob2}, critical = {critical2}, stat = {stat2}")
if abs(stat2)>=critical2:
    print('Dependent so reject Null hypothesis (H0)')
else:
    print('independent so accept Alternate hypothesis (Ha)')
    
#interpreting the P-value:

alpha2=1.0 - prob2
print(f"alpha = {alpha2}, p_value = {p2}")
if p2<=alpha:
    print("Dependent so reject null hypothesis (H0)")
else:
     print('independent so accept alternate hypothesis (Ha)')

P-value = 2.682172557281901e-17
Degrees of freedom = 3
[[111.01694915  91.21892655 113.05225989  77.71186441]
 [488.98305085 401.78107345 497.94774011 342.28813559]]
probability = 0.95, critical = 7.814727903251179, stat = 3.858960685820355
independent so accept Alternate hypothesis (Ha)
alpha = 0.050000000000000044, p_value = 0.2771020991233135
independent so accept alternate hypothesis (Ha)


In [31]:
from statsmodels.stats.proportion import proportions_ztest
count = np.array([520,280])
nobs = np.array([800,800])
stat,pval = proportions_ztest(count,nobs)
print(f'P value is{format(pval)}')
print(f'stat is {stat}')


P value is3.552964224155306e-33
stat is 12.000000000000002
